課題① 掲示板の機能追加
kaneyan0607/quelcode-php pull request #4
Opened 2020-06-01 16:10 UTC by kaneyan0607

# やったこと（Twitter風ひとこと掲示板への機能追加）
## RT（リツイート）機能を実装
- ボタンを押下すると、元の投稿をRTすることができる
- ボタン押下を繰り返すと、RTの取り消しを行うことができる
- RTされた件数が分かる
※TwitterのコメントなしのRTと同様の挙動
## いいね！ボタンを実装
- いいねボタンを押下すると、ボタンがいいね状態になる
- ボタン押下を繰り返すと、いいね数が+1、-1される（要は取り消しが可能）
- RTに対して いいね を押下した場合、RT元の投稿のいいね数が+1される。また、再びいいねボタンを押すとRT元の投稿のいいね数が-1される。

2020-06-02 07:09 UTC, choimake reviewed
コメントしましたので確認お願いします。

2020-06-02 07:09 UTC, choimake commented on html/php-challenge/like_add.php
> +            $_GET['post_id'], //いいねをする投稿されたツイートのid
整数の値が渡される想定の処理だと思いますが、現状の実装だと整数以外の値がきた場合でも、その値がDBに直接入力されてしまいます。
セキュリティ的に危険なので、整数以外の値がきた場合はそもそもSQLを実行せず、そのままリダイレクトするように修正してください。

他にも該当箇所があるので、それらも合わせて対応お願いします。

2020-06-02 07:09 UTC, choimake commented on mysql5.7/init.sql
> +    PRIMARY KEY (`id`)
(細かいですが)ここだけインデントがズレているので直しておいてください。

2020-06-02 09:18 UTC, kaneyan0607 commented
# やったこと
- 09aa89f こちらのコミットです。よろしくお願いします。
### いいね、リツイートの処理を修正（セキュリティ的に危険だった為）
- 0以上の整数、以外の値がきた場合SQLを実行せず、そのままリダイレクトするように修正
### init.sqlを修正
- インデントを揃えました。

2020-06-03 05:37 UTC, yusaku-inamura requested changes
レビューしてコメントしました。
一点気になった点として、少々コメントが過剰な気がしますね。
学習中ということもあるのでスルーはしますが、不要なコメントはコードを読みづらくする可能性がありますので、本当に必要なコメントかどうか少し気にしながら書くようにしてください

2020-06-03 05:37 UTC, yusaku-inamura commented on mysql5.7/init.sql
> +      `pressed_member_id` int(11) NOT NULL,
ここはそもそもいいね(like)テーブルですので、あまり `like~` というプレフィックスをつける必要は無いように感じます。
また、外部とのリレーションのキーとして使用するidのカラムなのであれば、基本的には `{リレーション先テーブル名}_id` の方がわかりやすいですね。
今回で言えば `post_id` 、 `member_id` となります

2020-06-03 05:37 UTC, yusaku-inamura commented on mysql5.7/init.sql
> +      `pressed_member_id` int(11) NOT NULL,
まあ厳格な決まりというわけでは無いので今回はこのままでいいです。
今後テーブル設計を行う際は気をつけましょう。

2020-06-03 05:37 UTC, yusaku-inamura commented on html/php-challenge/index.php
> +</html>
phpファイルなどに限らず、基本的に全てのファイルの終端は改行で終わらせるようにしてください。
理由としては、POSIXというapiの共通規格にて「行は改行で終わり、ファイルは行の集合である」と定義づけられているからです。

2020-06-03 05:37 UTC, yusaku-inamura commented on html/php-challenge/like_add.php
> +    if ((isset($_GET['post_id'])) && (preg_match('/^\d+$/', $_GET['post_id']))) { //0以上の整数か正規表現で判断
ここで0を含める必要ってありますかね?
理由含めて少し考えてみてください。

2020-06-03 05:37 UTC, yusaku-inamura commented on html/php-challenge/retweet_add.php
> +$retweetresponse = $db->prepare('SELECT m.name, m.picture, p.* FROM members m, posts p WHERE m.id=p.member_id AND p.id=?');
変数の命名規則について、ケースがあっていないのが所々散見されますね。
ファイルを見直してスネークケースならスネークケース、キャメルケースならキャメルケースで統一するようにしましょう。
一応僕が現場で見てきた中では比較的キャメルケースを採用していることが多いですが、特にこれとは決められていないので、統一さえされていればOKです

2020-06-03 05:37 UTC, yusaku-inamura commented on html/php-challenge/like_add.php
> +    } elseif (preg_match('/^\d+$/', $_GET['retweet_post_id'])) {
ここも整数であれば本当になんでもいいでしょうか?

2020-06-03 05:37 UTC, yusaku-inamura commented on mysql5.7/init.sql
> +      `retweet_post_id` int(11) NOT NULL,
ここはリツイートでは無い投稿の場合のことを考えると、not null制約は不要に感じますね。
これは元のDBの設計( `reply_post_id ` )がそうなっているのでしょうがないところではあるので、直す必要はないです。

2020-06-03 05:37 UTC, yusaku-inamura commented on html/php-challenge/index.php
> +								<a style="color:#0000FF;" href="retweet_delete.php?post_id=<?php echo h($post['retweet_post_id']); ?>"><i class="fas fa-retweet"></i></a>
表示はともかくとして、どの投稿を消すかの分岐については `retweet_delete.php` に移すことはできませんか?
ロジックは極力表示側に組み込まない方がみやすくなります

2020-06-03 05:37 UTC, yusaku-inamura commented on html/php-challenge/index.php
> +							<!--　いいね機能 $postはいいねをする投稿されたツイートのid $likeMessageは53行目で取得したもの $likeMessages_dbには自分がいいねしたツイートの値のみ入っている。-->
このコメントの書き方はあまりよろしくないですね。
このファイル内での修正が発生した場合にここも直す必要が出てきますし、仮に気づかなかった場合このコメントの意味があまりなくなってしまいます。

2020-06-03 05:37 UTC, yusaku-inamura commented on html/php-challenge/index.php
> +							<?php endif; ?>
ここもリツイートに対するいいねの挙動と本家RTのいいねに関する挙動の制御はそれぞれのファイル内に移すことができそうな気がしますね 🤔

2020-06-03 05:37 UTC, yusaku-inamura commented on html/php-challenge/index.php
> +							<?php endif; ?>
とりあえずここは動いているので検討は後回しでもいいです。

2020-06-03 05:37 UTC, yusaku-inamura commented on html/php-challenge/index.php
> +								<a style="color:#0000FF;" href="retweet_delete.php?post_id=<?php echo h($post['retweet_post_id']); ?>"><i class="fas fa-retweet"></i></a>
とりあえずここは動いているので検討は後回しでもいいです。

2020-06-03 06:35 UTC, kaneyan0607 commented on html/php-challenge/index.php
> +</html>
承知いたしました。
VScodeでも自動的に挿入されるよう設定し直しました。🙇‍♂️

2020-06-03 11:47 UTC, kaneyan0607 commented
# PHP掲示板課題の修正
- 3d1c2ebこちらのコミットです。よろしくお願いいたします。
## ファイルの終端は改行で終わるように修正
- VScodeでも自動的に挿入されるよう設定
## いいね、リツイートの処理を修正
- 1以上の整数、以外の値がきた場合SQLを実行せず、そのままリダイレクトするよう修正。
理由:0を含めない処理に変えた理由:0のpost_idは存在しないのにもかかわらず0を含めてしまうと、テーブルに存在しないはずの投稿である0番の投稿がINSERTされてしまう為。
前提条件として一般的にゼロ埋めを許容するのは、会員番号や ID のような何かを識別するためのコード値として利用するケースに限られる為、ゼロ埋め無しに変更。
## 不要なコメントアウトを削除
- 各ファイルに不要なコメントアウトが多く、コードが見づらくなっていた為コメントアウトを精査し、必要なものだけ残しました。

2020-06-03 11:55 UTC, kaneyan0607 commented on html/php-challenge/index.php
> +								<a style="color:#0000FF;" href="retweet_delete.php?post_id=<?php echo h($post['retweet_post_id']); ?>"><i class="fas fa-retweet"></i></a>
承知いたしました🙇‍♂️！

2020-06-03 11:55 UTC, kaneyan0607 commented on html/php-challenge/index.php
> +							<?php endif; ?>
承知いたしました🙇‍♂️！

2020-06-04 05:18 UTC, Yuzunoha commented
対応不要ですが
3d1c2ebecac93a6985f623a58775b9896803fcf1
このコミットはいろいろやりすぎていてよろしくないため

- Fix:いいね、リツイートファイルにて正規表現の条件を1以上に修正
- Fix:変数の命名規則をキャメルケースに統一
- Remove:不要なコメントアウトを削除

これらをそれぞれ独立したコミットにするべきです。

2020-06-04 05:25 UTC, Yuzunoha commented
OKです！！承認しました！！！

2020-06-04 05:25 UTC, Yuzunoha approved these changes
LGTM！

2020-06-04 05:29 UTC, Yuzunoha commented
下記のようなケースがあるためコミットはテーマ毎に分けるべきとされています
・どのコミットから動作不良になったのか調べる
・あるコミットだけ別のブランチに移植する(チェリーピック)

2020-06-04 06:23 UTC, merged